Repository PrestaShop/ui-testing-library, pull requests merged in 2024-06, with the labels that each got.

#45 Fix clickOnSaveProductButton method
  src/versions/develop/pages/BO/catalog/products/create/index.ts
Labels: TE, E2E Tests

#46 Add methods to get psVersion
  src/interfaces/BO/index.ts
  src/interfaces/BO/login/index.ts
  src/pages/BO/BOBasePage.ts
  src/versions/develop/pages/BO/login/index.ts
Labels: QA ✔️, TE

#49 Enable product pages for PS 8.0.x
  src/interfaces/BO/catalog/products/create/index.ts
  src/interfaces/BO/catalog/products/create/tabCombinations.ts
  src/interfaces/BO/catalog/products/create/tabDescription.ts
  src/interfaces/BO/catalog/products/create/tabPack.ts
  src/interfaces/BO/catalog/products/create/tabPricing.ts
  src/interfaces/BO/catalog/products/index.ts
  src/interfaces/BO/login/index.ts
  src/pages/BO/catalog/products/create/index.ts
  src/pages/BO/catalog/products/create/tabCombinations.ts
  src/pages/BO/catalog/products/create/tabDescription.ts
  src/pages/BO/catalog/products/create/tabDetails.ts
  src/pages/BO/catalog/products/create/tabPricing.ts
  src/pages/BO/catalog/products/create/tabStocks.ts
  src/pages/BO/catalog/products/create/tabVirtualProduct.ts
  src/pages/BO/catalog/products/index.ts
  src/versions/8.0/pages/BO/catalog/products/create/index.ts
  src/versions/8.0/pages/BO/catalog/products/create/tabCombinations.ts
  src/versions/8.0/pages/BO/catalog/products/create/tabDescription.ts
  src/versions/8.0/pages/BO/catalog/products/create/tabDetails.ts
  src/versions/8.0/pages/BO/catalog/products/create/tabPricing.ts
  src/versions/8.0/pages/BO/catalog/products/create/tabStocks.ts
  src/versions/8.0/pages/BO/catalog/products/create/tabVirtualProduct.ts
  src/versions/8.0/pages/BO/catalog/products/index.ts
  src/versions/8.1/pages/BO/catalog/products/index.ts
  src/versions/8.1/pages/BO/login/index.ts
  src/versions/develop/pages/BO/catalog/products/create/index.ts
  src/versions/develop/pages/BO/catalog/products/create/tabCombinations.ts
  src/versions/develop/pages/BO/catalog/products/create/tabDescription.ts
  src/versions/develop/pages/BO/catalog/products/create/tabDetails.ts
  src/versions/develop/pages/BO/catalog/products/create/tabPack.ts
  src/versions/develop/pages/BO/catalog/products/create/tabPricing.ts
  src/versions/develop/pages/BO/catalog/products/create/tabSeo.ts
  src/versions/develop/pages/BO/catalog/products/create/tabShipping.ts
  src/versions/develop/pages/BO/catalog/products/create/tabStocks.ts
  src/versions/develop/pages/BO/catalog/products/create/tabVirtualProduct.ts
  src/versions/develop/pages/BO/catalog/products/index.ts
  src/versions/develop/pages/BO/login/index.ts
Labels: QA ✔️, TE, E2E Tests

#50 Fix versions for create product pages
  src/pages/BO/catalog/products/create/index.ts
  src/pages/BO/catalog/products/create/tabCombinations.ts
  src/pages/BO/catalog/products/create/tabDescription.ts
  src/pages/BO/catalog/products/create/tabDetails.ts
  src/pages/BO/catalog/products/create/tabPricing.ts
  src/pages/BO/catalog/products/create/tabStocks.ts
  src/pages/BO/catalog/products/create/tabVirtualProduct.ts
Labels: TE, E2E Tests

#51 Fix reset Filter method in products page
  src/versions/develop/pages/BO/catalog/products/index.ts
Labels: QA ✔️, TE, E2E Tests

#52 Fix reset Filter in products page PS 8.0
  src/versions/8.0/pages/BO/catalog/products/index.ts
Labels: QA ✔️, TE, E2E Tests

#56 Moved POM `ps_newproducts` from Core
  src/index.ts
  src/interfaces/BO/modules/blockwishlist/index.ts
  src/interfaces/BO/modules/moduleConfiguration/index.ts
  src/interfaces/BO/modules/ps_newproducts/index.ts
  src/pages/BO/modules/moduleConfiguration/index.ts
  src/pages/BO/modules/ps_newproducts/index.ts
  src/versions/develop/pages/BO/modules/ps_newproducts/index.ts
Labels: QA ✔️

#57 Fix modify order status method
  src/versions/develop/pages/BO/orders/view/viewOrderBasePage.ts
Labels: QA ✔️

#59 Moved POM `@pages\shopParameters\search` from Core
  src/index.ts
  src/interfaces/BO/index.ts
  src/interfaces/BO/shopParameters/search/index.ts
  src/pages/BO/shopParameters/search/index.ts
  src/versions/develop/pages/BO/shopParameters/search/index.ts
Labels: enhancement

#62 `@pages\BO\BOBasePage` : Added some methods
  src/interfaces/BO/index.ts
Labels: QA ✔️, enhancement

#67 Migrate `@pages/BO/advancedParameters/performance` from Core
  src/index.ts
  src/interfaces/BO/advancedParameters/performance/index.ts
  src/pages/BO/advancedParameters/performance/index.ts
  src/versions/develop/pages/BO/advancedParameters/performance/index.ts
Labels: enhancement

#69 Migrate `@pages/BO/modules/moduleManager` & `@pages/BO/modules/moduleManager/alerts` from Core
  src/index.ts
  src/interfaces/BO/modules/moduleManager/alerts.ts
  src/interfaces/BO/modules/moduleManager/index.ts
  src/pages/BO/modules/moduleManager/alerts.ts
  src/pages/BO/modules/moduleManager/index.ts
  src/versions/develop/pages/BO/modules/moduleManager/alerts.ts
  src/versions/develop/pages/BO/modules/moduleManager/index.ts
Labels: enhancement

#71 `@pages/BO/shopParameters/search` : Added methods for the maximum approximate words allowed by fuzzy search
  src/data/demo/products.ts
  src/interfaces/BO/shopParameters/search/index.ts
  src/versions/develop/pages/BO/shopParameters/search/index.ts
Labels: QA ✔️, enhancement
