Repository PrestaShop/ui-testing-library, pull requests merged in 2024-10, with the labels that each got.

#160 `setFormProductAndSales` : Added method `setFormProductAndSales`
  src/interfaces/BO/dashboard/index.ts
  src/versions/develop/pages/BO/dashboard/index.ts
Labels: QA ✔️, enhancement, TE, E2E Tests

#161 `boDashboardPage` : Added methods for Activity Overview Form
  src/data/types/dashboard.ts
  src/index.ts
  src/interfaces/BO/dashboard/index.ts
  src/versions/develop/pages/BO/dashboard/index.ts
Labels: QA ✔️, enhancement, TE, E2E Tests

#162 Migrate `@pages/BO/advancedParameters/database/sqlManager` from Core
  src/index.ts
  src/interfaces/BO/advancedParameters/database/sqlManager/create.ts
  src/interfaces/BO/advancedParameters/database/sqlManager/index.ts
  src/interfaces/BO/advancedParameters/database/sqlManager/view.ts
  src/pages/BO/advancedParameters/database/sqlManager/create.ts
  src/pages/BO/advancedParameters/database/sqlManager/index.ts
  src/pages/BO/advancedParameters/database/sqlManager/view.ts
  src/versions/develop/pages/BO/advancedParameters/database/sqlManager/create.ts
  src/versions/develop/pages/BO/advancedParameters/database/sqlManager/index.ts
  src/versions/develop/pages/BO/advancedParameters/database/sqlManager/view.ts
Labels: QA ✔️, enhancement, TE, E2E Tests

#163 Migrate @pages/BO/design/emailThemes/preview from Core
  src/index.ts
  src/interfaces/BO/design/emailThemes/index.ts
  src/interfaces/BO/design/emailThemes/preview.ts
  src/interfaces/BO/index.ts
  src/pages/BO/BOBasePage.ts
  src/pages/BO/design/emailThemes/preview.ts
  src/versions/develop/pages/BO/design/emailThemes/index.ts
  src/versions/develop/pages/BO/design/emailThemes/preview.ts
Labels: QA ✔️

#165 Migrate `@pages/BO/shopParameters/orderSettings` from Core
  src/index.ts
  src/interfaces/BO/shopParameters/orderSettings/index.ts
  src/pages/BO/shopParameters/orderSettings/index.ts
  src/versions/develop/pages/BO/shopParameters/orderSettings/index.ts
Labels: QA ✔️, enhancement, TE, E2E Tests

#167 `modBlockwishlistBoStatistics` : Add method for fetching the number of products
  src/interfaces/BO/modules/blockwishlist/statistics.ts
  src/versions/develop/pages/BO/modules/blockwishlist/statistics.ts
Labels: QA ✔️, enhancement, TE, E2E Tests

#168 `modBlockwishlistBoMain` : Get & Set Labels
  src/interfaces/BO/modules/blockwishlist/index.ts
  src/interfaces/FO/modal/wishlist.ts
  src/versions/develop/pages/BO/modules/blockwishlist/index.ts
  src/versions/develop/pages/FO/classic/modal/wishlist.ts
Labels: QA ✔️, enhancement, TE, E2E Tests

#169 Migrate `@pages/BO/advancedParameters/email` from Core
  src/index.ts
  src/interfaces/BO/advancedParameters/email.ts
  src/pages/BO/advancedParameters/email.ts
  src/versions/develop/pages/BO/advancedParameters/email.ts
Labels: QA ✔️, enhancement, TE, E2E Tests

#171 Migrate `@pages/BO/quickAccess` from Core
  src/index.ts
  src/interfaces/BO/quickAccess/index.ts
  src/pages/BO/quickAccess/index.ts
  src/versions/develop/pages/BO/quickAccess/index.ts
Labels: enhancement, TE, E2E Tests

#172 `FakerShop` : Add id & theme
  src/data/faker/shop.ts
  src/data/types/shop.ts
Labels: QA ✔️, enhancement, TE, E2E Tests

#173 Migrate `@pages/FO/{classic|hummingbird}/contactUs` from Core
  src/index.ts
  src/interfaces/FO/contactUs/index.ts
  src/pages/FO/classic/contactUs/index.ts
  src/pages/FO/hummingbird/contactUs/index.ts
  src/versions/develop/pages/FO/classic/contactUs/index.ts
  src/versions/develop/pages/FO/hummingbird/contactUs/index.ts
Labels: QA ✔️, enhancement, TE, E2E Tests

#175 Migrate `@pages/BO/advancedParameters/featureFlag` from Core
  src/index.ts
  src/interfaces/BO/advancedParameters/featureFlag.ts
  src/pages/BO/advancedParameters/featureFlag.ts
  src/versions/develop/pages/BO/advancedParameters/featureFlag.ts
Labels: QA ✔️, enhancement, TE, E2E Tests

#177 Migrate `@pages/BO/advancedParameters/import` from Core
  src/index.ts
  src/interfaces/BO/advancedParameters/import.ts
  src/pages/BO/advancedParameters/import.ts
  src/versions/develop/pages/BO/advancedParameters/import.ts
Labels: QA ✔️, enhancement, TE, E2E Tests

#176 `foClassicCategoryPage` : Added method `isSearchFilterSlider`
  src/interfaces/FO/category/index.ts
  src/versions/develop/pages/FO/classic/category/index.ts
  src/versions/develop/pages/FO/hummingbird/category/index.ts
Labels: QA ✔️, enhancement, TE, E2E Tests

#191 Migrate link list pages from core
  src/data/demo/hooks.ts
  src/data/faker/linkWidget.ts
  src/data/types/linkWidget.ts
  src/index.ts
  src/interfaces/BO/design/linkList/create.ts
  src/interfaces/BO/design/linkList/index.ts
  src/pages/BO/design/linkList/create.ts
  src/pages/BO/design/linkList/index.ts
  src/versions/develop/pages/BO/design/linkList/create.ts
  src/versions/develop/pages/BO/design/linkList/index.ts
Labels: QA ✔️

#193 Added type exports for Playwright
  src/index.ts
Labels: QA ✔️, enhancement, TE, E2E Tests

#203 Bump `@playwright/test` to `1.48.0`: Fixed some errors
  src/versions/develop/pages/BO/catalog/products/create/index.ts
  src/versions/develop/pages/BO/catalog/products/index.ts
Labels: QA ✔️

#207 Migrate `@pages/BO/catalog/attributes` from Core
  src/index.ts
  src/interfaces/BO/catalog/attributes/index.ts
  src/interfaces/BO/index.ts
  src/pages/BO/catalog/attributes/index.ts
  src/pages/commonPage.ts
  src/versions/develop/pages/BO/catalog/attributes/index.ts
Labels: QA ✔️, TE, E2E Tests

#209 `boModuleManagerPage`: `getModuleInformationNth` returns the status of installation
  src/data/types/module.ts
  src/versions/develop/pages/BO/modules/moduleManager/index.ts
Labels: QA ✔️, enhancement, TE, E2E Tests

#210 Add pages for 1.7.7 version
  src/pages/BO/catalog/products/create/tabDescription.ts
  src/pages/BO/orders/index.ts
  src/pages/FO/classic/home/index.ts
  src/pages/FO/classic/product/index.ts
  src/versions/1.7.7/pages/BO/catalog/products/create/tabDescription.ts
  src/versions/1.7.7/pages/BO/orders/index.ts
  src/versions/1.7.7/pages/FO/classic/home/index.ts
  src/versions/1.7.7/pages/FO/classic/product/index.ts
  src/versions/develop/pages/BO/orders/index.ts
  src/versions/develop/pages/BO/orders/view/blockProducts.ts
Labels: QA ✔️

#213 `boModuleManagerPage` : Fixed the `enabled` key
  src/versions/develop/pages/BO/modules/moduleManager/index.ts
Labels: bug, TE, E2E Tests

#220 `modPsCategoryProductsBoMain` : Added the new page
  src/index.ts
  src/interfaces/BO/modules/ps_categoryproducts/index.ts
  src/interfaces/FO/product/index.ts
  src/pages/BO/modules/ps_categoryproducts/index.ts
  src/versions/develop/pages/BO/modules/ps_categoryproducts/index.ts
  src/versions/develop/pages/FO/classic/product/index.ts
Labels: QA ✔️

#221 Migrate `@pages/BO/design/positions` from Core
  src/interfaces/BO/design/positions/index.ts
  src/versions/develop/pages/BO/design/positions/index.ts
Labels: QA ✔️, enhancement, TE, E2E Tests

#226 `boSearchPage` : Added method setSearchWithinWord
  src/interfaces/BO/shopParameters/search/index.ts
  src/versions/develop/pages/BO/shopParameters/search/index.ts
Labels: QA ✔️, enhancement, TE, E2E Tests
