Repository PrestaShop/ui-testing-library, pull requests merged in 2024-05, with the labels that each got.

#29 Enable boLoginPage in the Core
  src/interfaces/BO/login/index.ts
  src/pages/BO/login/index.ts
  src/versions/1.7.8/pages/BO/login/index.ts
  src/versions/8.1/pages/BO/login/index.ts
  src/versions/develop/pages/BO/login/index.ts
Labels: QA ✔️, TE, E2E Tests

#31 Fix Orders view pages
  src/interfaces/BO/orders/view/productsBlock.ts
  src/versions/develop/pages/BO/orders/view/productsBlock.ts
Labels: QA ✔️, TE, E2E Tests

#32 Enable product page and data
  src/data/types/product.ts
  src/index.ts
  src/interfaces/BO/catalog/products/create/combinationsTab.ts
  src/interfaces/BO/catalog/products/create/descriptionTab.ts
  src/interfaces/BO/catalog/products/create/detailsTab.ts
  src/interfaces/BO/catalog/products/create/index.ts
  src/interfaces/BO/catalog/products/create/optionsTab.ts
  src/interfaces/BO/catalog/products/create/packTab.ts
  src/interfaces/BO/catalog/products/create/pricingTab.ts
  src/interfaces/BO/catalog/products/create/seoTab.ts
  src/interfaces/BO/catalog/products/create/shippingTab.ts
  src/interfaces/BO/catalog/products/create/stocksTab.ts
  src/interfaces/BO/catalog/products/create/virtualProductTab.ts
  src/interfaces/BO/catalog/products/index.ts
  src/pages/BO/catalog/products/create/combinationsTab.ts
  src/pages/BO/catalog/products/create/descriptionTab.ts
  src/pages/BO/catalog/products/create/detailsTab.ts
  src/pages/BO/catalog/products/create/index.ts
  src/pages/BO/catalog/products/create/optionsTab.ts
  src/pages/BO/catalog/products/create/packTab.ts
  src/pages/BO/catalog/products/create/pricingTab.ts
  src/pages/BO/catalog/products/create/seoTab.ts
  src/pages/BO/catalog/products/create/shippingTab.ts
  src/pages/BO/catalog/products/create/stocksTab.ts
  src/pages/BO/catalog/products/create/virtualProductTab.ts
  src/pages/BO/catalog/products/index.ts
  src/versions/develop/pages/BO/catalog/products/create/combinationsTab.ts
  src/versions/develop/pages/BO/catalog/products/create/descriptionTab.ts
  src/versions/develop/pages/BO/catalog/products/create/detailsTab.ts
  src/versions/develop/pages/BO/catalog/products/create/index.ts
  src/versions/develop/pages/BO/catalog/products/create/optionsTab.ts
  src/versions/develop/pages/BO/catalog/products/create/packTab.ts
  src/versions/develop/pages/BO/catalog/products/create/pricingTab.ts
  src/versions/develop/pages/BO/catalog/products/create/seoTab.ts
  src/versions/develop/pages/BO/catalog/products/create/shippingTab.ts
  src/versions/develop/pages/BO/catalog/products/create/stocksTab.ts
  src/versions/develop/pages/BO/catalog/products/create/virtualProductTab.ts
  src/versions/develop/pages/BO/catalog/products/index.ts
Labels: QA ✔️, TE, E2E Tests

#33 Add category data
  src/data/demo/categories.ts
  src/data/demo/products.ts
  src/data/faker/category.ts
  src/data/types/category.d.ts
  src/index.ts
Labels: TE, E2E Tests

#34 Enable FO product page
  src/data/faker/productReview.ts
  src/index.ts
  src/interfaces/BO/index.ts
  src/interfaces/FO/product/index.ts
  src/pages/FO/classic/product/index.ts
  src/versions/develop/pages/FO/classic/product/index.ts
Labels: TE, E2E Tests

#35 Add basic helper
  src/index.ts
  src/utils/basicHelper.ts
Labels: TE, E2E Tests

#37 Refactoring BO Products Create tabs
  src/index.ts
  src/interfaces/BO/catalog/products/create/index.ts
  src/interfaces/BO/catalog/products/create/tabCombinations.ts
  src/interfaces/BO/catalog/products/create/tabDescription.ts
  src/interfaces/BO/catalog/products/create/tabDetails.ts
  src/interfaces/BO/catalog/products/create/tabOptions.ts
  src/interfaces/BO/catalog/products/create/tabPack.ts
  src/interfaces/BO/catalog/products/create/tabPricing.ts
  src/interfaces/BO/catalog/products/create/tabSeo.ts
  src/interfaces/BO/catalog/products/create/tabShipping.ts
  src/interfaces/BO/catalog/products/create/tabStocks.ts
  src/interfaces/BO/catalog/products/create/tabVirtualProduct.ts
  src/pages/BO/catalog/products/create/combinationsTab.ts
  src/pages/BO/catalog/products/create/descriptionTab.ts
  src/pages/BO/catalog/products/create/detailsTab.ts
  src/pages/BO/catalog/products/create/index.ts
  src/pages/BO/catalog/products/create/optionsTab.ts
  src/pages/BO/catalog/products/create/packTab.ts
  src/pages/BO/catalog/products/create/pricingTab.ts
  src/pages/BO/catalog/products/create/seoTab.ts
  src/pages/BO/catalog/products/create/shippingTab.ts
  src/pages/BO/catalog/products/create/stocksTab.ts
  src/pages/BO/catalog/products/create/tabCombinations.ts
  src/pages/BO/catalog/products/create/tabDescription.ts
  src/pages/BO/catalog/products/create/tabDetails.ts
  src/pages/BO/catalog/products/create/tabOptions.ts
  src/pages/BO/catalog/products/create/tabPack.ts
  src/pages/BO/catalog/products/create/tabPricing.ts
  src/pages/BO/catalog/products/create/tabSeo.ts
  src/pages/BO/catalog/products/create/tabShipping.ts
  src/pages/BO/catalog/products/create/tabStocks.ts
  src/pages/BO/catalog/products/create/tabVirtualProduct.ts
  src/pages/BO/catalog/products/create/virtualProductTab.ts
  src/versions/develop/pages/BO/catalog/products/create/index.ts
  src/versions/develop/pages/BO/catalog/products/create/tabCombinations.ts
  src/versions/develop/pages/BO/catalog/products/create/tabDescription.ts
  src/versions/develop/pages/BO/catalog/products/create/tabDetails.ts
  src/versions/develop/pages/BO/catalog/products/create/tabOptions.ts
  src/versions/develop/pages/BO/catalog/products/create/tabPack.ts
  src/versions/develop/pages/BO/catalog/products/create/tabPricing.ts
  src/versions/develop/pages/BO/catalog/products/create/tabSeo.ts
  src/versions/develop/pages/BO/catalog/products/create/tabShipping.ts
  src/versions/develop/pages/BO/catalog/products/create/tabStocks.ts
  src/versions/develop/pages/BO/catalog/products/create/tabVirtualProduct.ts
Labels: QA ✔️

#38 Update FO category interface
  src/interfaces/FO/category/index.ts
Labels: QA ✔️, TE, E2E Tests

#41 Enable Quick view and Block Cart modals
  src/data/types/product.ts
  src/index.ts
  src/interfaces/FO/cart/index.ts
  src/interfaces/FO/checkout/orderConfirmation.ts
  src/interfaces/FO/modal/blockCart.ts
  src/interfaces/FO/modal/quickView.ts
  src/pages/BO/catalog/products/index.ts
  src/pages/FO/classic/modal/blockCart.ts
  src/pages/FO/classic/modal/quickView.ts
  src/versions/develop/pages/FO/classic/cart/index.ts
  src/versions/develop/pages/FO/classic/modal/blockCart.ts
  src/versions/develop/pages/FO/classic/modal/quickView.ts
Labels: TE, E2E Tests
