Repository PrestaShop/ui-testing-library, pull requests merged in 2024-11, with the labels that each got.

#233 `boSearchPage` : Added method `clickRebuildEntireIndex`
  src/interfaces/BO/shopParameters/search/index.ts
  src/versions/develop/pages/BO/shopParameters/search/index.ts
Labels: enhancement, TE, E2E Tests

#234 Migrate `@pages/BO/catalog/products/add/detailsTab` from Core
  src/interfaces/BO/catalog/products/create/tabDetails.ts
  src/versions/develop/pages/BO/catalog/products/create/tabDetails.ts
Labels: QA ✔️, enhancement, TE, E2E Tests

#236 Migrate 173 selectors to run sanity tests
  src/pages/BO/BOBasePage.ts
  src/pages/BO/catalog/products/create/index.ts
  src/pages/BO/catalog/products/index.ts
  src/versions/1.7.3/pages/BO/catalog/products/create/index.ts
  src/versions/1.7.3/pages/BO/catalog/products/index.ts
  src/versions/develop/pages/BO/catalog/products/create/index.ts
  src/versions/develop/pages/BO/catalog/products/index.ts
Labels: QA ✔️

#237 Migrate `@pages/BO/catalog/products/add/pricingTab` from Core
  src/data/types/product.ts
  src/interfaces/BO/catalog/products/create/tabPricing.ts
  src/versions/develop/pages/BO/catalog/products/create/tabPricing.ts
Labels: enhancement, TE, E2E Tests

#238 Add filter product method in 173
  src/versions/1.7.3/pages/BO/catalog/products/index.ts
  src/versions/develop/pages/BO/catalog/products/index.ts
Labels: QA ✔️

#243 `boModuleManagerPage` : Added delete module message
  src/interfaces/BO/modules/moduleManager/index.ts
  src/versions/develop/pages/BO/modules/moduleManager/index.ts
Labels: QA ✔️, enhancement, TE, E2E Tests

#244 Add methods in cart page and Adapt sanity tests with 1.7.2
  src/data/demo/categories.ts
  src/data/demo/products.ts
  src/interfaces/FO/cart/index.ts
  src/pages/BO/catalog/products/create/index.ts
  src/pages/BO/catalog/products/index.ts
  src/pages/BO/login/index.ts
  src/pages/BO/orders/index.ts
  src/pages/BO/orders/view/viewOrderBasePage.ts
  src/pages/FO/FOBasePage.ts
  src/pages/FO/classic/login/index.ts
  src/versions/1.7.2/pages/BO/catalog/products/create/index.ts
  src/versions/1.7.2/pages/BO/catalog/products/index.ts
  src/versions/1.7.2/pages/BO/login/index.ts
  src/versions/1.7.2/pages/BO/orders/index.ts
  src/versions/1.7.2/pages/BO/orders/view/viewOrderBasePage.ts
  src/versions/1.7.2/pages/FO/classic/login/index.ts
  src/versions/1.7.6/pages/BO/orders/index.ts
  src/versions/1.7.6/pages/BO/orders/view/viewOrderBasePage.ts
  src/versions/1.7.8/pages/BO/login/index.ts
  src/versions/develop/pages/BO/login/index.ts
  src/versions/develop/pages/FO/classic/cart/index.ts
  src/versions/develop/pages/FO/classic/login/index.ts
  src/versions/develop/pages/FO/classic/product/index.ts
Labels: QA ✔️

#245 Fix go to submenu method
  src/pages/FO/FOBasePage.ts
Labels: QA ✔️

#249 Fix login to 172
  src/versions/1.7.2/pages/BO/login/index.ts
Labels: QA ✔️

#252 `boSearchPage` : Added get/set weight input & `FakerProduct` : Added brand & tags
  src/data/faker/product.ts
  src/data/types/product.ts
  src/data/types/search.ts
  src/interfaces/BO/catalog/products/create/tabDescription.ts
  src/interfaces/BO/shopParameters/search/index.ts
  src/versions/develop/pages/BO/catalog/products/create/index.ts
  src/versions/develop/pages/BO/catalog/products/create/tabDescription.ts
  src/versions/develop/pages/BO/catalog/products/create/tabDetails.ts
  src/versions/develop/pages/BO/shopParameters/search/index.ts
Labels: QA ✔️, enhancement, TE, E2E Tests

#253 Migrate `@pages/BO/catalog/brands` from Core
  src/index.ts
  src/interfaces/BO/catalog/brands/index.ts
  src/pages/BO/catalog/brands/index.ts
  src/versions/develop/pages/BO/catalog/brands/index.ts
Labels: QA ✔️, enhancement, TE, E2E Tests

#254 `boProductsCreateTabDetailsPage` : Fixed features
  src/interfaces/BO/catalog/products/create/tabDetails.ts
  src/versions/develop/pages/BO/catalog/products/create/tabDetails.ts
Labels: bug, TE, E2E Tests

#257 `utilsPlaywright` : Improve system for capturing errors
  src/data/types/globals.ts
  src/utils/playwright.ts
Labels: enhancement, TE, E2E Tests

#258 `FakerSearchTag` : Use only products from last version of PrestaShop
  src/data/demo/products.ts
  src/data/faker/cartRule.ts
  src/data/faker/searchTag.ts
Labels: QA ✔️, bug, TE, E2E Tests

#266 Update Keycloak module version
  src/data/demo/modules.ts
Labels: QA ✔️

#268 `boStatisticsPage` : Added page
  src/data/demo/modules.ts
  src/index.ts
  src/interfaces/BO/index.ts
  src/interfaces/BO/statistics/index.ts
  src/pages/BO/BOBasePage.ts
  src/pages/BO/statistics/index.ts
  src/versions/develop/pages/BO/statistics/index.ts
Labels: TE, E2E Tests
