Repository PrestaShop/ui-testing-library, pull requests merged in 2024-12, with the labels that each got.

#274 `boModuleManagerUpdatesPage` : Added page
  src/index.ts
  src/interfaces/BO/modules/moduleManager/index.ts
  src/interfaces/BO/modules/moduleManager/updates.ts
  src/pages/BO/modules/moduleManager/updates.ts
  src/versions/develop/pages/BO/modules/moduleManager/index.ts
  src/versions/develop/pages/BO/modules/moduleManager/updates.ts
Labels: TE, E2E Tests

#278 `boThemeAndLogoChooseLayoutsPage` : Added Page
  src/index.ts
  src/interfaces/BO/design/themeAndLogo/index.ts
  src/interfaces/BO/design/themeAndLogo/themeAndLogo/chooseLayouts.ts
  src/pages/BO/design/themeAndLogo/themeAndLogo/chooseLayouts.ts
  src/versions/develop/pages/BO/design/themeAndLogo/index.ts
  src/versions/develop/pages/BO/design/themeAndLogo/themeAndLogo/chooseLayouts.ts
Labels: QA ✔️, enhancement, TE, E2E Tests

#287 `FOBasePage` : Fixed `clickOnBreadCrumbLink` method
  src/pages/FO/FOBasePage.ts
Labels: QA ✔️, bug, TE, E2E Tests

#294 `@playwright/test` : Set version to 1.49.1
  package-lock.json
  src/versions/develop/pages/BO/catalog/products/index.ts
Labels: bug, TE, E2E Tests

#300 Add data and pages for autoupgrade module
  src/data/demo/modules.ts
  src/index.ts
  src/interfaces/BO/modules/autoupgrade/index.ts
  src/pages/BO/modules/autoupgrade/index.ts
  src/versions/develop/pages/BO/modules/autoupgrade/index.ts
Labels: QA ✔️

#305 Add methods to install module for all PS versions
  src/index.ts
  src/interfaces/BO/modules/marketplace/index.ts
  src/interfaces/BO/modules/moduleCatalog/index.ts
  src/interfaces/BO/modules/modulesAndServices/installedModules.ts
  src/interfaces/BO/modules/modulesAndServices/selection.ts
  src/pages/BO/modules/marketplace/index.ts
  src/pages/BO/modules/moduleCatalog/index.ts
  src/pages/BO/modules/modulesAndServices/installedModules.ts
  src/pages/BO/modules/modulesAndServices/selection.ts
  src/versions/1.7.0/pages/BO/modules/modulesAndServices/selection.ts
  src/versions/1.7.1/pages/BO/modules/modulesAndServices/installedModules.ts
  src/versions/1.7.1/pages/BO/modules/modulesAndServices/selection.ts
  src/versions/1.7.2/pages/BO/modules/modulesAndServices/installedModules.ts
  src/versions/1.7.2/pages/BO/modules/modulesAndServices/selection.ts
  src/versions/1.7.4/pages/BO/modules/modulesAndServices/installedModules.ts
  src/versions/1.7.4/pages/BO/modules/modulesAndServices/selection.ts
  src/versions/1.7.5/pages/BO/modules/marketplace/index.ts
  src/versions/1.7.6/pages/BO/modules/moduleCatalog/index.ts
  src/versions/mock/pages/BO/modules/marketplace/index.ts
  src/versions/mock/pages/BO/modules/modulesAndServices/installedModules.ts
  src/versions/mock/pages/BO/modules/modulesAndServices/selection.ts
Labels: enhancement, TE, E2E Tests
