Repository PrestaShop/ui-testing-library, pull requests merged in 2024-07, with the labels that each got.

#72 Migrate `@pages/FO/{classic|hummingbird}/modal/quickView` from Core
  src/index.ts
  src/pages/FO/classic/modal/quickView.ts
  src/pages/FO/hummingbird/modal/quickView.ts
  src/versions/develop/pages/FO/hummingbird/modal/quickView.ts
Labels: QA ✔️

#74 Migrate `@pages/FO/{classic|hummingbird}/login` from Core
  src/index.ts
  src/interfaces/FO/login/index.ts
  src/pages/FO/hummingbird/login/index.ts
  src/versions/develop/pages/FO/classic/login/index.ts
  src/versions/develop/pages/FO/hummingbird/login/index.ts
Labels: QA ✔️, enhancement

#77 Migrate `@pages/FO/classic/aboutUs` & `@pages/FO/hummingbird/aboutUs` from Core
  src/index.ts
  src/interfaces/FO/aboutUs/index.ts
  src/pages/FO/classic/aboutUs/index.ts
  src/pages/FO/hummingbird/aboutUs/index.ts
  src/versions/develop/pages/FO/classic/aboutUs/index.ts
  src/versions/develop/pages/FO/hummingbird/aboutUs/index.ts
Labels: QA ✔️

#78 Moved `@pages/BO/international/localization` from Core
  src/index.ts
  src/interfaces/BO/international/localization/base.ts
  src/interfaces/BO/international/localization/index.ts
  src/interfaces/index.ts
  src/pages/BO/international/localization/base.ts
  src/pages/BO/international/localization/index.ts
  src/pages/commonPage.ts
  src/versions/develop/pages/BO/international/localization/index.ts
Labels: QA ✔️, enhancement

#79 Move `@pages/BO/payment/paymentMethods` from Core
  src/index.ts
  src/interfaces/BO/payment/paymentMethods/index.ts
  src/pages/BO/payment/paymentMethods/index.ts
  src/versions/develop/pages/BO/payment/paymentMethods/index.ts
Labels: enhancement

#80 Migrate `@pages/FO/{classic|hummingbird}/myAccount/myWishlists` from Core
  src/index.ts
  src/interfaces/FO/myAccount/myWishlists/index.ts
  src/interfaces/FO/myAccount/myWishlists/view.ts
  src/pages/FO/classic/myAccount/myWishlists/index.ts
  src/pages/FO/classic/myAccount/myWishlists/view.ts
  src/pages/FO/hummingbird/myAccount/myWishlists/index.ts
  src/versions/develop/pages/FO/classic/myAccount/myWishlists/index.ts
  src/versions/develop/pages/FO/classic/myAccount/myWishlists/view.ts
  src/versions/develop/pages/FO/hummingbird/myAccount/myWishlists/index.ts
Labels: QA ✔️

#81 `check:data:modules` : Update `@data/demo/modules` every night
  .github/workflows/updateModules.yml
  package-lock.json
  package.json
  src/data/demo/modules.ts
  src/versions/develop/pages/FO/classic/myAccount/myWishlists/index.ts
Labels: enhancement

#83 `@pages/FO/classic/modal/wishlist` : Added modal share & create
  src/interfaces/FO/modal/wishlist.ts
  src/interfaces/FO/myAccount/myWishlists/index.ts
  src/versions/develop/pages/FO/classic/modal/wishlist.ts
  src/versions/develop/pages/FO/classic/myAccount/myWishlists/index.ts
Labels: QA ✔️, enhancement

#84 Migrate `@pages/FO/{classic|hummingbird}/myAccount` from Core
  src/index.ts
  src/interfaces/FO/myAccount/index.ts
  src/pages/FO/classic/myAccount/index.ts
  src/pages/FO/hummingbird/myAccount/index.ts
  src/versions/develop/pages/FO/classic/myAccount/index.ts
  src/versions/develop/pages/FO/hummingbird/myAccount/index.ts
Labels: QA ✔️, enhancement

#85 Fix Random error in click on add product method
  src/versions/develop/pages/BO/catalog/products/index.ts
Labels: QA ✔️

#86 `@pages/BO/shopParameters/search` : Added methods for Indexing block
  src/interfaces/BO/shopParameters/search/index.ts
  src/versions/develop/pages/BO/shopParameters/search/index.ts
Labels: enhancement

#88 `@pages/BO/modules/ps_facetedsearch/filterTemplate` : Added filter for "Product condition filter"
  src/versions/develop/pages/BO/modules/ps_facetedsearch/filterTemplate.ts
Labels: QA ✔️, enhancement

#90 `@pages/BO/shopParameters/search` : Added methods for "Search exact end match"
  src/interfaces/BO/shopParameters/search/index.ts
  src/versions/develop/pages/BO/shopParameters/search/index.ts
  src/versions/develop/pages/FO/classic/home/index.ts
Labels: QA ✔️, enhancement

#91 Migrate `@pages/BO/catalog/products` from Core
  src/interfaces/BO/catalog/products/index.ts
  src/interfaces/BO/index.ts
  src/versions/develop/pages/BO/catalog/products/index.ts
Labels: QA ✔️, enhancement

#92 `@pages/BO/modules/ps_facetedsearch/filterTemplate` : Added filter for "Sub-categories filter"
  src/versions/develop/pages/BO/modules/ps_facetedsearch/filterTemplate.ts
Labels: QA ✔️, enhancement

#93 Migrate `@pages/FO/{classic|hummingbird}/product` from Core
  src/index.ts
  src/interfaces/FO/product/index.ts
  src/interfaces/index.ts
  src/pages/FO/classic/product/index.ts
  src/pages/FO/hummingbird/product/index.ts
  src/pages/commonPage.ts
  src/versions/develop/pages/FO/classic/product/index.ts
  src/versions/develop/pages/FO/hummingbird/product/index.ts
Labels: enhancement

#95 `@pages/BO/modules/moduleManager` : `setActionInModule` : Cancel when disable mode
  src/versions/develop/pages/BO/modules/moduleManager/index.ts
Labels: QA ✔️

#96 Migrate `@pages/BO/design/themeAndLogo` from Core
  src/index.ts
  src/interfaces/BO/design/themeAndLogo/advancedConfiguration.ts
  src/interfaces/BO/design/themeAndLogo/base.ts
  src/interfaces/BO/design/themeAndLogo/index.ts
  src/interfaces/BO/design/themeAndLogo/pagesConfiguration.ts
  src/interfaces/BO/design/themeAndLogo/themeAndLogo/import.ts
  src/pages/BO/design/themeAndLogo/advancedConfiguration.ts
  src/pages/BO/design/themeAndLogo/base.ts
  src/pages/BO/design/themeAndLogo/index.ts
  src/pages/BO/design/themeAndLogo/pagesConfiguration.ts
  src/pages/BO/design/themeAndLogo/themeAndLogo/import.ts
  src/versions/develop/pages/BO/design/themeAndLogo/advancedConfiguration.ts
  src/versions/develop/pages/BO/design/themeAndLogo/index.ts
  src/versions/develop/pages/BO/design/themeAndLogo/pagesConfiguration.ts
  src/versions/develop/pages/BO/design/themeAndLogo/themeAndLogo/import.ts
Labels: enhancement

#97 `@pages/BO/design/themeAndLogo` : Fixed import
  src/pages/BO/design/themeAndLogo/advancedConfiguration.ts
  src/pages/BO/design/themeAndLogo/index.ts
  src/pages/BO/design/themeAndLogo/pagesConfiguration.ts
Labels: bug

#98 `@pages/BO/design/themeAndLogo` : Fixed import (2)
  src/pages/BO/design/themeAndLogo/themeAndLogo/import.ts
Labels: bug

#94 Added `opsBOModules` & `opsBOProducts`
  src/index.ts
  src/ops/BO/catalog/product.ts
  src/ops/BO/modules/moduleManager.ts
  src/pages/BO/BOBasePage.ts
  src/pages/FO/classic/home/index.ts
  src/versions/8.0/pages/BO/catalog/products/index.ts
  src/versions/8.1/pages/BO/catalog/products/index.ts
  src/versions/8.1/pages/FO/classic/home/index.ts
  tsconfig.json
Labels: QA ✔️, enhancement

#99 Migrate `@pages/BO/international/locations/countries` from Core
  src/index.ts
  src/interfaces/BO/international/locations/countries/create.ts
  src/interfaces/BO/international/locations/countries/index.ts
  src/pages/BO/international/locations/countries/create.ts
  src/pages/BO/international/locations/countries/index.ts
  src/versions/develop/pages/BO/international/locations/countries/create.ts
  src/versions/develop/pages/BO/international/locations/countries/index.ts
Labels: enhancement

#100 `@pages/BO/advancedParameters/information` : Added new page
  src/index.ts
  src/interfaces/BO/advancedParameters/information/index.ts
  src/pages/BO/advancedParameters/information/index.ts
  src/versions/develop/pages/BO/advancedParameters/information/index.ts
Labels: QA ✔️, enhancement

#101 Migrate `@pages/BO/advancedParameters/administration` from Core
  src/index.ts
  src/interfaces/BO/advancedParameters/administration/index.ts
  src/interfaces/BO/index.ts
  src/pages/BO/advancedParameters/administration/index.ts
  src/versions/develop/pages/BO/advancedParameters/administration/index.ts
Labels: QA ✔️, enhancement

#102 `@pages/FO/classic/product` : Added method for checking the if the wishlist button is present
  src/data/demo/modules.ts
  src/interfaces/FO/product/index.ts
  src/versions/develop/pages/FO/classic/product/index.ts
Labels: enhancement

#103 Migrate `@pages/BO/advancedParameters/apiclients` from Core
  src/index.ts
  src/interfaces/BO/advancedParameters/apiclients/create.ts
  src/interfaces/BO/advancedParameters/apiclients/index.ts
  src/interfaces/BO/index.ts
  src/pages/BO/advancedParameters/apiclients/create.ts
  src/pages/BO/advancedParameters/apiclients/index.ts
  src/versions/develop/pages/BO/advancedParameters/apiclients/create.ts
  src/versions/develop/pages/BO/advancedParameters/apiclients/index.ts
Labels: QA ✔️, enhancement

#104 Multiples enhancements for UI Tests
  src/data/demo/products.ts
  src/interfaces/BO/advancedParameters/performance/index.ts
  src/interfaces/BO/catalog/products/index.ts
  src/interfaces/FO/product/index.ts
  src/versions/develop/pages/BO/advancedParameters/performance/index.ts
  src/versions/develop/pages/BO/catalog/products/index.ts
  src/versions/develop/pages/FO/classic/product/index.ts
Labels: QA ✔️, enhancement

#107 `@pages/BO/modules/ps_facetedsearch/filterTemplate` : Added filter for "Attribute group: Paper Type"
  src/versions/develop/pages/BO/modules/ps_facetedsearch/filterTemplate.ts
Labels: enhancement

#108 Migrate `@pages/BO/modules/psEmailSubscription` from Core
  src/index.ts
  src/interfaces/BO/index.ts
  src/interfaces/BO/modules/ps_emailsubscription/index.ts
  src/pages/BO/modules/ps_emailsubscription/index.ts
  src/versions/develop/pages/BO/modules/ps_emailsubscription/index.ts
Labels: enhancement

#111 Migrate `@pages/FO/classic/emailSubscription` from Core
  src/index.ts
  src/interfaces/FO/emailSubscription/index.ts
  src/pages/FO/classic/emailSubscription/index.ts
  src/versions/develop/pages/FO/classic/emailSubscription/index.ts
Labels: enhancement

#112 Migrate `@pages/FO/{classic|hummingbird}/passwordReminder` from Core
  src/index.ts
  src/interfaces/FO/passwordReminder/index.ts
  src/pages/FO/classic/passwordReminder/index.ts
  src/pages/FO/hummingbird/passwordReminder/index.ts
  src/versions/develop/pages/FO/classic/passwordReminder/index.ts
  src/versions/develop/pages/FO/hummingbird/passwordReminder/index.ts
Labels: QA ✔️, enhancement
