Repository PrestaShop/ui-testing-library, pull requests merged in 2025-02, with the labels that each got.

#391 Wait for ajax call to end when adding a product in order creation
  src/versions/develop/pages/BO/orders/create.ts
Labels: bug

#392 `boCartRulesPage` : Fixed filter for date
  src/utils/date.ts
  src/versions/develop/pages/BO/catalog/discounts/index.ts
Labels: QA ✔️, enhancement, TE, E2E Tests

#297 `boCarriersPage` : Adapt the page for v9
  src/pages/BO/shipping/carriers/create.ts
  src/pages/BO/shipping/carriers/index.ts
  src/versions/8.2/pages/BO/shipping/carriers/create.ts
  src/versions/8.2/pages/BO/shipping/carriers/index.ts
  src/versions/develop/pages/BO/shipping/carriers/create.ts
  src/versions/develop/pages/BO/shipping/carriers/index.ts
Labels: TE, E2E Tests

#398 `boDesignPositionsPage` : Added `getHookTitle` method
  src/interfaces/BO/design/positions/index.ts
  src/versions/develop/pages/BO/design/positions/index.ts
Labels: enhancement, TE, E2E Tests

#408 Migrate `@pages/BO/catalog/brands/addAddress` from Core
  src/index.ts
  src/interfaces/BO/catalog/brands/addresses/create.ts
  src/pages/BO/catalog/brands/addresses/create.ts
  src/versions/develop/pages/BO/catalog/brands/addresses/create.ts
Labels: enhancement, TE, E2E Tests

#409 Migrate `@pages/BO/catalog/brands/add` from Core
  src/index.ts
  src/interfaces/BO/catalog/brands/create.ts
  src/pages/BO/catalog/brands/create.ts
  src/versions/develop/pages/BO/catalog/brands/create.ts
Labels: enhancement, TE, E2E Tests

#410 Migrate `@pages/BO/catalog/brands/view` from Core
  src/index.ts
  src/interfaces/BO/catalog/brands/view.ts
  src/pages/BO/catalog/brands/view.ts
  src/versions/develop/pages/BO/catalog/brands/view.ts
Labels: enhancement, TE, E2E Tests

#411 Migrate `@pages/BO/catalog/suppliers` from Core
  src/index.ts
  src/interfaces/BO/catalog/suppliers/index.ts
  src/pages/BO/catalog/suppliers/index.ts
  src/versions/develop/pages/BO/catalog/suppliers/index.ts
Labels: enhancement, TE, E2E Tests

#413 Migrate `@pages/BO/catalog/suppliers/view` from Core
  src/index.ts
  src/interfaces/BO/catalog/suppliers/view.ts
  src/pages/BO/catalog/suppliers/view.ts
  src/versions/develop/pages/BO/catalog/suppliers/view.ts
Labels: enhancement, TE, E2E Tests

#414 Migrate `@pages/BO/catalog/files/add` from Core
  src/index.ts
  src/interfaces/BO/catalog/files/create.ts
  src/pages/BO/catalog/files/create.ts
  src/versions/develop/pages/BO/catalog/files/create.ts
Labels: enhancement, TE, E2E Tests

#415 Migrate `@pages/FO/{classic|hummingbird}/myAccount/vouchers` from Core
  src/index.ts
  src/interfaces/FO/myAccount/vouchers.ts
  src/pages/FO/classic/myAccount/vouchers.ts
  src/pages/FO/hummingbird/myAccount/vouchers.ts
  src/versions/develop/pages/FO/classic/myAccount/vouchers.ts
  src/versions/develop/pages/FO/hummingbird/myAccount/vouchers.ts
Labels: enhancement, TE, E2E Tests

#417 Migrate `@pages/BO/international/locations` from Core
  src/index.ts
  src/interfaces/BO/international/locations/index.ts
  src/pages/BO/international/locations/index.ts
  src/versions/develop/pages/BO/international/locations/index.ts
Labels: enhancement, TE, E2E Tests

#418 Migrate `@pages/FO/{classic|hummingbird}/myAccount/add` from Core
  src/index.ts
  src/interfaces/FO/myAccount/create.ts
  src/pages/FO/classic/myAccount/create.ts
  src/pages/FO/hummingbird/myAccount/create.ts
  src/versions/develop/pages/FO/classic/myAccount/create.ts
  src/versions/develop/pages/FO/hummingbird/myAccount/create.ts
Labels: enhancement, TE, E2E Tests

#421 Migrate `@pages/FO/{classic|hummingbird}/myAccount/addresses` from Core
  src/index.ts
  src/interfaces/FO/myAccount/addresses.ts
  src/pages/FO/classic/myAccount/addresses.ts
  src/pages/FO/hummingbird/myAccount/addresses.ts
  src/versions/develop/pages/FO/classic/myAccount/addresses.ts
  src/versions/develop/pages/FO/hummingbird/myAccount/addresses.ts
Labels: enhancement, TE, E2E Tests

#422 Migrate `@pages/FO/{classic|hummingbird}/myAccount/addAddresses` from Core
  src/index.ts
  src/interfaces/FO/myAccount/addresses/create.ts
  src/pages/FO/classic/myAccount/addresses/create.ts
  src/pages/FO/hummingbird/myAccount/addresses/create.ts
  src/versions/develop/pages/FO/classic/myAccount/addresses/create.ts
  src/versions/develop/pages/FO/hummingbird/myAccount/addresses/create.ts
Labels: enhancement, TE, E2E Tests

#423 Migrate `@pages/BO/customers/outstanding` from Core
  src/index.ts
  src/interfaces/BO/catalog/outstanding.ts
  src/pages/BO/catalog/outstanding.ts
  src/versions/develop/pages/BO/catalog/outstanding.ts
Labels: enhancement, TE, E2E Tests

#424 Migrate `@pages/BO/customerService/customerService/view` from Core
  src/index.ts
  src/interfaces/BO/customerService/customerService/view.ts
  src/pages/BO/customerService/customerService/view.ts
  src/versions/develop/pages/BO/customerService/customerService/view.ts
Labels: enhancement, TE, E2E Tests

#425 Migrate `@pages/BO/customerService/orderMessages/add` from Core
  src/index.ts
  src/interfaces/BO/customerService/orderMessages/create.ts
  src/pages/BO/customerService/orderMessages/create.ts
  src/versions/develop/pages/BO/customerService/orderMessages/create.ts
Labels: enhancement, TE, E2E Tests

#426 Migrate `@pages/BO/modules/psCheckPayment` from Core
  src/index.ts
  src/interfaces/BO/modules/ps_checkpayment/index.ts
  src/pages/BO/modules/ps_checkpayment/index.ts
  src/versions/develop/pages/BO/modules/ps_checkpayment/index.ts
Labels: enhancement, TE, E2E Tests

#427 Migrate `@pages/BO/modules/contactform` from Core
  src/index.ts
  src/interfaces/BO/modules/contactform/index.ts
  src/pages/BO/modules/contactform/index.ts
  src/versions/develop/pages/BO/modules/contactform/index.ts
Labels: enhancement, TE, E2E Tests

#428 Migrate `@pages/BO/modules/moduleConfiguration` from Core
  src/index.ts
  src/pages/BO/modules/moduleConfiguration/index.ts
  src/versions/develop/pages/BO/modules/autoupgrade/index.ts
  src/versions/develop/pages/BO/modules/blockwishlist/index.ts
  src/versions/develop/pages/BO/modules/blockwishlist/statistics.ts
  src/versions/develop/pages/BO/modules/contactform/index.ts
  src/versions/develop/pages/BO/modules/keycloakConnectorDemo/index.ts
  src/versions/develop/pages/BO/modules/moduleConfiguration/index.ts
  src/versions/develop/pages/BO/modules/productcomments/index.ts
  src/versions/develop/pages/BO/modules/ps_categoryproducts/index.ts
  src/versions/develop/pages/BO/modules/ps_checkpayment/index.ts
  src/versions/develop/pages/BO/modules/ps_emailalerts/index.ts
  src/versions/develop/pages/BO/modules/ps_emailsubscription/index.ts
  src/versions/develop/pages/BO/modules/ps_facetedsearch/filterTemplate.ts
  src/versions/develop/pages/BO/modules/ps_facetedsearch/index.ts
  src/versions/develop/pages/BO/modules/ps_newproducts/index.ts
  src/versions/develop/pages/BO/modules/ps_supplierlist/index.ts
  src/versions/develop/pages/BO/modules/ps_wirepayment/index.ts
  src/versions/develop/pages/BO/modules/psgdpr/index.ts
  src/versions/develop/pages/BO/modules/psgdpr/tabCustomerActivity.ts
  src/versions/develop/pages/BO/modules/psgdpr/tabDataConfig.ts
  src/versions/develop/pages/BO/modules/psgdpr/tabDataConsent.ts
  src/versions/develop/pages/BO/modules/psgdpr/tabHelp.ts
Labels: enhancement, TE, E2E Tests

#430 Migrate `@pages/BO/design/pages/pageCategory/add` from Core
  src/index.ts
  src/interfaces/BO/design/pages/category/create.ts
  src/pages/BO/design/pages/category/create.ts
  src/versions/develop/pages/BO/design/pages/category/create.ts
Labels: enhancement, TE, E2E Tests

#436 Migrate `@pages/BO/design/pages/add` from Core
  src/index.ts
  src/interfaces/BO/design/pages/create.ts
  src/pages/BO/design/pages/create.ts
  src/versions/develop/pages/BO/design/pages/create.ts
Labels: enhancement, TE, E2E Tests

#437 Migrate `@pages/FO/{classic|hummingbird}/cms` from Core
  src/index.ts
  src/interfaces/FO/cms.ts
  src/pages/FO/classic/cms.ts
  src/pages/FO/hummingbird/cms.ts
  src/versions/develop/pages/FO/classic/cms.ts
  src/versions/develop/pages/FO/hummingbird/cms.ts
Labels: enhancement, TE, E2E Tests

#438 Migrate `@pages/BO/design/imageSettings` from Core
  src/index.ts
  src/interfaces/BO/design/imageSettings/index.ts
  src/pages/BO/design/imageSettings/index.ts
  src/versions/develop/pages/BO/design/imageSettings/index.ts
Labels: enhancement, TE, E2E Tests

#439 Migrate `@pages/BO/design/imageSettings/add` from Core
  src/index.ts
  src/interfaces/BO/design/imageSettings/create.ts
  src/pages/BO/design/imageSettings/create.ts
  src/versions/develop/pages/BO/design/imageSettings/create.ts
Labels: enhancement, TE, E2E Tests

#440 Migrate `@pages/BO/shopParameters/contact` from Core
  src/index.ts
  src/interfaces/BO/shopParameters/contacts/index.ts
  src/pages/BO/shopParameters/contacts/index.ts
  src/versions/develop/pages/BO/shopParameters/contacts/index.ts
Labels: enhancement, TE, E2E Tests

#441 Migrate `@pages/BO/shopParameters/stores` from Core
  src/index.ts
  src/interfaces/BO/shopParameters/stores/index.ts
  src/pages/BO/shopParameters/stores/index.ts
  src/versions/develop/pages/BO/shopParameters/stores/index.ts
Labels: enhancement, TE, E2E Tests

#442 Migrate `@pages/BO/shopParameters/stores/add` from Core
  src/index.ts
  src/interfaces/BO/shopParameters/stores/create.ts
  src/pages/BO/shopParameters/stores/create.ts
  src/versions/develop/pages/BO/shopParameters/stores/create.ts
Labels: enhancement, TE, E2E Tests

#443 Migrate `@pages/FO/{classic|hummingbird}/stores` from Core
  src/index.ts
  src/interfaces/FO/stores.ts
  src/pages/FO/classic/stores.ts
  src/pages/FO/hummingbird/stores.ts
  src/versions/develop/pages/FO/classic/stores.ts
  src/versions/develop/pages/FO/hummingbird/stores.ts
Labels: enhancement, TE, E2E Tests

#444 Migrate `@pages/BO/shipping/preferences` from Core
  src/index.ts
  src/interfaces/BO/shipping/preferences.ts
  src/pages/BO/shipping/preferences.ts
  src/versions/develop/pages/BO/shipping/preferences.ts
Labels: enhancement, TE, E2E Tests

#446 Migrate `@pages/BO/international/localization/geolocation` from Core
  src/index.ts
  src/interfaces/BO/international/localization/geolocation.ts
  src/pages/BO/international/localization/geolocation.ts
  src/versions/develop/pages/BO/international/localization/geolocation.ts
Labels: enhancement, TE, E2E Tests

#447 Migrate `@pages/BO/international/locations/add` from Core
  src/index.ts
  src/interfaces/BO/international/locations/create.ts
  src/pages/BO/international/locations/create.ts
  src/versions/develop/pages/BO/international/locations/create.ts
Labels: enhancement, TE, E2E Tests
