Repository PrestaShop/ui-testing-library, pull requests merged in 2025-04, with the labels that each got.

#510 `foHummingbirdModalQuickViewPage` : Improve closeQuickViewModal method
  src/versions/develop/pages/FO/classic/modal/quickView.ts
Labels: enhancement, TE, E2E Tests

#511 `demoProducts` : Added name for `demo_17`
  src/data/demo/products.ts
Labels: bug, TE, E2E Tests

#520 Migrate `@pages/FO/{classic|hummingbird}/legalNotice` from Core
  src/index.ts
  src/interfaces/FO/legalNotice.ts
  src/pages/FO/classic/legalNotice.ts
  src/pages/FO/hummingbird/legalNotice.ts
  src/versions/develop/pages/FO/classic/legalNotice.ts
  src/versions/develop/pages/FO/hummingbird/legalNotice.ts
Labels: enhancement, TE, E2E Tests

#521 Migrate `@pages/FO/{classic|hummingbird}/myAccount/creditSlips` from Core
  src/index.ts
  src/interfaces/FO/myAccount/creditSlips.ts
  src/pages/FO/classic/myAccount/creditSlips.ts
  src/pages/FO/hummingbird/myAccount/creditSlips.ts
  src/versions/develop/pages/FO/classic/myAccount/creditSlips.ts
  src/versions/develop/pages/FO/hummingbird/myAccount/creditSlips.ts
Labels: enhancement, TE, E2E Tests

#522 Migrate `@pages/FO/{classic|hummingbird}/myAccount/identity` from Core
  src/index.ts
  src/interfaces/FO/myAccount/informations.ts
  src/pages/FO/classic/myAccount/informations.ts
  src/pages/FO/hummingbird/myAccount/informations.ts
  src/versions/develop/pages/FO/classic/myAccount/informations.ts
  src/versions/develop/pages/FO/hummingbird/myAccount/informations.ts
Labels: enhancement, TE, E2E Tests

#536 `boProductsCreatePage` : Change the page title
  src/versions/develop/pages/BO/catalog/products/create/index.ts
Labels: bug, TE, E2E Tests

#544 Fix category selector to be unique
  src/pages/FO/FOBasePage.ts
Labels: bug
