Repository PrestaShop/ui-testing-library, pull requests merged in 2025-01, with the labels that each got.

#312 Adapt maintenance page with all versions
  src/pages/BO/modules/autoupgrade/index.ts
  src/pages/BO/shopParameters/general/maintenance.ts
  src/versions/1.7.3/pages/BO/modules/autoupgrade/index.ts
  src/versions/1.7.3/pages/BO/shopParameters/general/maintenance.ts
  src/versions/1.7.7/pages/BO/shopParameters/general/maintenance.ts
  src/versions/develop/pages/BO/modules/autoupgrade/index.ts
  src/versions/develop/pages/BO/shopParameters/general/maintenance.ts
Labels: QA ✔️

#313 Fix Module Configuration Button for PS version < 1.7.4
  src/versions/1.7.4/pages/BO/modules/modulesAndServices/installedModules.ts
  src/versions/develop/pages/BO/modules/autoupgrade/index.ts
Labels: QA ✔️

#321 Migrate `@pages/BO/advancedParameters/logs` from Core
  src/index.ts
  src/interfaces/BO/advancedParameters/logs.ts
  src/pages/BO/advancedParameters/logs.ts
  src/versions/develop/pages/BO/advancedParameters/logs.ts
Labels: enhancement, TE, E2E Tests

#322 Migrate `@pages/BO/orders/creditSlips` from Core
  src/index.ts
  src/interfaces/BO/orders/creditSlips.ts
  src/pages/BO/orders/creditSlips.ts
  src/versions/develop/pages/BO/orders/creditSlips.ts
Labels: enhancement, TE, E2E Tests

#323 Migrate `@pages/BO/customers/add` from Core
  src/index.ts
  src/interfaces/BO/customers/create.ts
  src/interfaces/BO/index.ts
  src/pages/BO/customers/create.ts
  src/versions/develop/pages/BO/customers/create.ts
Labels: enhancement, TE, E2E Tests

#324 Migrate `@pages/BO/orders/add` from Core
  src/index.ts
  src/interfaces/BO/orders/create.ts
  src/pages/BO/orders/create.ts
  src/versions/develop/pages/BO/orders/create.ts
Labels: enhancement, TE, E2E Tests

#325 Migrate `@pages/BO/orders/deliverySlips` from Core
  src/index.ts
  src/interfaces/BO/orders/deliverySlips.ts
  src/pages/BO/orders/deliverySlips.ts
  src/versions/develop/pages/BO/orders/deliverySlips.ts
Labels: enhancement, TE, E2E Tests

#326 Migrate `@pages/BO/orders/invoices` from Core
  src/index.ts
  src/interfaces/BO/orders/invoices.ts
  src/pages/BO/orders/invoices.ts
  src/versions/develop/pages/BO/orders/invoices.ts
Labels: enhancement, TE, E2E Tests

#327 Migrate `@pages/BO/catalog/attributes/addAttribute` from Core
  src/index.ts
  src/interfaces/BO/catalog/attributes/createAttribute.ts
  src/pages/BO/catalog/attributes/createAttribute.ts
  src/versions/develop/pages/BO/catalog/attributes/createAttribute.ts
Labels: enhancement, TE, E2E Tests

#328 Migrate `@pages/BO/catalog/products/add` from Core
  src/interfaces/BO/catalog/products/create/index.ts
  src/interfaces/BO/index.ts
  src/pages/BO/catalog/products/create/index.ts
  src/versions/1.7.2/pages/BO/catalog/products/create/index.ts
  src/versions/1.7.3/pages/BO/catalog/products/create/index.ts
  src/versions/1.7.5/pages/BO/catalog/products/create/index.ts
  src/versions/8.0/pages/BO/catalog/products/create/index.ts
  src/versions/8.1/pages/BO/catalog/suppliers/create.ts
  src/versions/8.2/pages/BO/catalog/products/create/index.ts
  src/versions/develop/pages/BO/catalog/products/create/index.ts
Labels: enhancement, TE, E2E Tests

#337 `boProductsCreateTab*Page` : Fixed some issues
  src/interfaces/BO/catalog/products/create/tabCombinations.ts
  src/versions/develop/pages/BO/catalog/products/create/index.ts
  src/versions/develop/pages/BO/catalog/products/create/tabCombinations.ts
  src/versions/develop/pages/BO/catalog/products/create/tabOptions.ts
  src/versions/develop/pages/BO/catalog/products/create/tabSeo.ts
Labels: bug

#338 `boProductsCreateTabPackPage` : Fixed export
  src/pages/BO/catalog/products/create/tabPack.ts
  src/versions/develop/pages/BO/catalog/products/create/index.ts
  src/versions/develop/pages/BO/catalog/products/create/tabPack.ts
Labels: bug

#340 Migrate `@pages/BO/catalog/monitoring` from Core
  src/index.ts
  src/interfaces/BO/catalog/monitoring.ts
  src/pages/BO/catalog/monitoring.ts
  src/versions/develop/pages/BO/catalog/monitoring.ts
Labels: enhancement, TE, E2E Tests

#341 Migrate `@pages/BO/customerService/customerService` from Core
  src/index.ts
  src/interfaces/BO/customerService/customerService/index.ts
  src/pages/BO/customerService/customerService/index.ts
  src/versions/develop/pages/BO/customerService/customerService/index.ts
Labels: enhancement, TE, E2E Tests

#342 Migrate `@pages/BO/modules/productComments` from Core
  src/index.ts
  src/interfaces/BO/modules/autoupgrade/index.ts
  src/interfaces/BO/modules/productcomments/index.ts
  src/pages/BO/modules/productcomments/index.ts
  src/versions/develop/pages/BO/modules/productcomments/index.ts
Labels: enhancement, TE, E2E Tests

#343 Migrate `@pages/FO/{classic|hummingbird}/myAccount/orderHistory` from Core
  src/index.ts
  src/interfaces/FO/myAccount/orderHistory.ts
  src/pages/FO/classic/myAccount/orderHistory.ts
  src/pages/FO/hummingbird/myAccount/orderHistory.ts
  src/versions/develop/pages/FO/classic/myAccount/orderHistory.ts
  src/versions/develop/pages/FO/hummingbird/myAccount/orderHistory.ts
Labels: enhancement, TE, E2E Tests

#345 Migrate `@pages/FO/{classic|hummingbird}/myAccount/merchandiseReturns` from Core
  src/index.ts
  src/interfaces/FO/myAccount/merchandiseReturns.ts
  src/pages/FO/classic/myAccount/merchandiseReturns.ts
  src/pages/FO/hummingbird/myAccount/merchandiseReturns.ts
  src/versions/develop/pages/FO/classic/myAccount/merchandiseReturns.ts
  src/versions/develop/pages/FO/hummingbird/myAccount/merchandiseReturns.ts
Labels: enhancement, TE, E2E Tests

#346 Migrate `@pages/BO/orders/view/customerBlock` from Core
  src/index.ts
  src/interfaces/BO/customers/addresses/create.ts
  src/interfaces/BO/orders/view/blockCustomers.ts
  src/pages/BO/customers/addresses/create.ts
  src/pages/BO/orders/view/blockCustomers.ts
  src/versions/develop/pages/BO/customers/addresses/create.ts
  src/versions/develop/pages/BO/orders/view/blockCustomers.ts
  src/versions/develop/pages/BO/orders/view/viewOrderBasePage.ts
Labels: enhancement, TE, E2E Tests

#347 Migrate `@pages/BO/orders/view/messagesBlock` from Core
  src/index.ts
  src/interfaces/BO/orders/view/blockMessages.ts
  src/interfaces/BO/orders/view/viewOrderBasePage.ts
  src/pages/BO/orders/view/blockMessages.ts
  src/versions/develop/pages/BO/orders/view/blockMessages.ts
Labels: enhancement, TE, E2E Tests

#348 Migrate `@pages/BO/orders/view/paymentsBlock` from Core
  src/index.ts
  src/interfaces/BO/orders/view/blockPayments.ts
  src/pages/BO/orders/view/blockPayments.ts
  src/versions/develop/pages/BO/orders/view/blockPayments.ts
Labels: enhancement, TE, E2E Tests

#349 Migrate `'@pages/BO/customers/view` from Core
  src/index.ts
  src/interfaces/BO/customers/view.ts
  src/pages/BO/customers/view.ts
  src/versions/develop/pages/BO/customers/view.ts
Labels: enhancement, TE, E2E Tests

#350 Migrate `@pages/BO/orders/shoppingCarts/view` from Core
  src/index.ts
  src/interfaces/BO/orders/shoppingCarts/view.ts
  src/pages/BO/orders/shoppingCarts/view.ts
  src/versions/develop/pages/BO/orders/shoppingCarts/view.ts
Labels: enhancement, TE, E2E Tests

#351 Migrate `@pages/BO/catalog/discounts` from Core
  src/index.ts
  src/interfaces/BO/catalog/discounts/index.ts
  src/pages/BO/catalog/discounts/index.ts
  src/versions/develop/pages/BO/catalog/discounts/index.ts
Labels: enhancement, TE, E2E Tests

#352 Migrate `@pages/BO/catalog/discounts/add` from Core
  src/index.ts
  src/interfaces/BO/catalog/discounts/create.ts
  src/interfaces/BO/index.ts
  src/pages/BO/catalog/discounts/create.ts
  src/versions/develop/pages/BO/catalog/discounts/create.ts
Labels: enhancement, TE, E2E Tests

#353 Migrate `@pages/BO/customers/addresses` from Core
  src/index.ts
  src/interfaces/BO/customers/addresses/index.ts
  src/pages/BO/customers/addresses/index.ts
  src/versions/develop/pages/BO/customers/addresses/index.ts
Labels: enhancement, TE, E2E Tests

#354 Migrate `@pages/BO/customerService/merchandiseReturns/edit` from Core
  src/index.ts
  src/interfaces/BO/customerService/merchandiseReturns/edit.ts
  src/pages/BO/customerService/merchandiseReturns/edit.ts
  src/versions/develop/pages/BO/customerService/merchandiseReturns/edit.ts
Labels: enhancement, TE, E2E Tests

#355 Migrate `@pages/BO/customerService/orderMessages` from Core
  src/index.ts
  src/interfaces/BO/customerService/orderMessages/index.ts
  src/pages/BO/customerService/orderMessages/index.ts
  src/versions/develop/pages/BO/customerService/orderMessages/index.ts
Labels: enhancement, TE, E2E Tests

#356 `foClassicMyOrderDetailsPage` : Fixed import
  src/index.ts
Labels: TE, E2E Tests

#329 Add @pages/BO/advancedParameters/security for Core
  src/index.ts
  src/interfaces/BO/advancedParameters/security/customerSessions/index.ts
  src/interfaces/BO/advancedParameters/security/employeeSessions/index.ts
  src/interfaces/BO/advancedParameters/security/index.ts
  src/pages/BO/advancedParameters/security/customerSessions/index.ts
  src/pages/BO/advancedParameters/security/employeeSessions/index.ts
  src/pages/BO/advancedParameters/security/index.ts
  src/versions/develop/pages/BO/advancedParameters/security/customerSessions/index.ts
  src/versions/develop/pages/BO/advancedParameters/security/employeeSessions/index.ts
  src/versions/develop/pages/BO/advancedParameters/security/index.ts
Labels: enhancement, TE, E2E Tests

#362 Migrate `@pages/BO/international/taxes` from Core
  src/index.ts
  src/interfaces/BO/international/taxes/index.ts
  src/pages/BO/international/taxes/index.ts
  src/versions/develop/pages/BO/international/taxes/index.ts
Labels: enhancement, TE, E2E Tests

#363 Migrate `@pages/BO/international/taxes/taxRules/add` from Core
  src/index.ts
  src/interfaces/BO/international/taxes/taxRules/create.ts
  src/pages/BO/international/taxes/taxRules/create.ts
  src/versions/develop/pages/BO/international/taxes/taxRules/create.ts
Labels: enhancement, TE, E2E Tests

#364 Migrate `@pages/BO/international/taxes/taxRules` from Core
  src/index.ts
  src/interfaces/BO/international/taxes/taxRules/index.ts
  src/pages/BO/international/taxes/taxRules/index.ts
  src/versions/develop/pages/BO/international/taxes/taxRules/index.ts
Labels: enhancement, TE, E2E Tests

#365 Migrate `@pages/BO/catalog/features` from Core
  src/index.ts
  src/interfaces/BO/catalog/features/index.ts
  src/pages/BO/catalog/features/index.ts
  src/versions/develop/pages/BO/catalog/features/index.ts
Labels: enhancement, TE, E2E Tests

#366 Migrate `@pages/BO/catalog/files` from Core
  src/index.ts
  src/interfaces/BO/catalog/files/index.ts
  src/pages/BO/catalog/files/index.ts
  src/versions/develop/pages/BO/catalog/files/index.ts
Labels: enhancement, TE, E2E Tests

#367 Migrate `@pages/BO/catalog/stocks/movements` from Core
  src/index.ts
  src/interfaces/BO/catalog/stock/movements.ts
  src/pages/BO/catalog/stock/movements.ts
  src/versions/develop/pages/BO/catalog/stock/movements.ts
Labels: enhancement, TE, E2E Tests

#368 Migrate `@pages/BO/catalog/discounts/catalogPriceRules/add` from Core
  src/index.ts
  src/interfaces/BO/catalog/discounts/catalogPriceRules/create.ts
  src/pages/BO/catalog/discounts/catalogPriceRules/create.ts
  src/versions/develop/pages/BO/catalog/discounts/catalogPriceRules/create.ts
Labels: enhancement, TE, E2E Tests

#369 Migrate `@pages/BO/catalog/discounts/catalogPriceRules` from Core
  src/index.ts
  src/interfaces/BO/catalog/discounts/catalogPriceRules/index.ts
  src/pages/BO/catalog/discounts/catalogPriceRules/index.ts
  src/versions/develop/pages/BO/catalog/discounts/catalogPriceRules/index.ts
Labels: enhancement, TE, E2E Tests

#370 Migrate `@pages/BO/advancedParameters/multistore` from Core
  src/index.ts
  src/interfaces/BO/advancedParameters/multistore/index.ts
  src/pages/BO/advancedParameters/multistore/index.ts
  src/versions/develop/pages/BO/advancedParameters/multistore/index.ts
Labels: enhancement, TE, E2E Tests

#371 Migrate `@pages/BO/advancedParameters/multistore/shop/add` from Core
  src/index.ts
  src/interfaces/BO/advancedParameters/multistore/shop/create.ts
  src/pages/BO/advancedParameters/multistore/shop/create.ts
  src/versions/develop/pages/BO/advancedParameters/multistore/shop/create.ts
Labels: enhancement, TE, E2E Tests

#372 Migrate `@pages/BO/advancedParameters/multistore/shop` from Core
  src/index.ts
  src/interfaces/BO/advancedParameters/multistore/shop/index.ts
  src/pages/BO/advancedParameters/multistore/shop/index.ts
  src/versions/develop/pages/BO/advancedParameters/multistore/shop/index.ts
Labels: enhancement, TE, E2E Tests

#373 Migrate `@pages/BO/advancedParameters/multistore/url/addURL` from Core
  src/index.ts
  src/interfaces/BO/advancedParameters/multistore/url/create.ts
  src/pages/BO/advancedParameters/multistore/url/create.ts
  src/versions/develop/pages/BO/advancedParameters/multistore/url/create.ts
Labels: enhancement, TE, E2E Tests

#374 Migrate `@pages/BO/catalog/categories` from Core
  src/index.ts
  src/interfaces/BO/catalog/categories/index.ts
  src/pages/BO/catalog/categories/index.ts
  src/versions/develop/pages/BO/catalog/categories/index.ts
Labels: enhancement, TE, E2E Tests

#375 Migrate `@pages/BO/catalog/categories/create` from Core
  src/index.ts
  src/interfaces/BO/catalog/categories/create.ts
  src/pages/BO/catalog/categories/create.ts
  src/versions/develop/pages/BO/catalog/categories/create.ts
Labels: enhancement, TE, E2E Tests

#376 Migrate `@pages/FO/{classic|hummingbird}/siteMap` from Core
  src/index.ts
  src/interfaces/FO/sitemap.ts
  src/pages/FO/classic/sitemap.ts
  src/pages/FO/hummingbird/sitemap.ts
  src/versions/develop/pages/FO/classic/sitemap.ts
  src/versions/develop/pages/FO/hummingbird/sitemap.ts
Labels: enhancement, TE, E2E Tests

#378 Migrate `@pages/BO/catalog/attributes/addValue` from Core
  src/index.ts
  src/interfaces/BO/catalog/attributes/createValue.ts
  src/pages/BO/catalog/attributes/createValue.ts
  src/versions/develop/pages/BO/catalog/attributes/createValue.ts
Labels: enhancement, TE, E2E Tests

#379 Migrate `@pages/BO/catalog/features/addFeature` from Core
  src/index.ts
  src/interfaces/BO/catalog/features/create.ts
  src/pages/BO/catalog/features/create.ts
  src/versions/develop/pages/BO/catalog/features/create.ts
Labels: enhancement, TE, E2E Tests

#380 Migrate `@pages/BO/catalog/features/view` from Core
  src/index.ts
  src/interfaces/BO/catalog/features/view.ts
  src/pages/BO/catalog/features/view.ts
  src/versions/develop/pages/BO/catalog/features/view.ts
Labels: enhancement, TE, E2E Tests

#381 Migrate `@pages/BO/catalog/features/addValue` from Core
  src/index.ts
  src/interfaces/BO/catalog/features/createValue.ts
  src/pages/BO/catalog/features/createValue.ts
  src/versions/develop/pages/BO/catalog/features/createValue.ts
Labels: enhancement, TE, E2E Tests
